import { createClient } from "@/utils/supabase/client";
import type { Vehicle } from "@/lib/types";

const fromRow = (row: Record<string, unknown>): Vehicle => ({
  id: String(row.id), slug: String(row.slug), name: String(row.name), model: String(row.model ?? ""), description: String(row.description ?? ""), shortDescription: String(row.short_description ?? ""), pricePerDay: Number(row.price_per_day ?? 0), securityDeposit: Number(row.security_deposit ?? 0), passengerCapacity: Number(row.passenger_capacity ?? 1), sleepingCapacity: Number(row.sleeping_capacity ?? 1), fuelType: row.fuel_type as Vehicle["fuelType"], transmission: row.transmission as Vehicle["transmission"], dimensions: (row.dimensions ?? {}) as Vehicle["dimensions"], drivingRequirements: (row.driving_requirements ?? []) as string[], amenities: (row.amenities ?? []) as string[], facilities: (row.facilities ?? {}) as Vehicle["facilities"], images: (row.images ?? []) as string[], videoUrl: row.video_url as string | undefined, status: row.status as Vehicle["status"], featured: Boolean(row.featured), createdAt: String(row.created_at ?? ""), updatedAt: String(row.updated_at ?? ""),
});

const toRow = (vehicle: Vehicle) => ({ id: vehicle.id === "new" ? undefined : vehicle.id, slug: vehicle.slug, name: vehicle.name, model: vehicle.model, description: vehicle.description, short_description: vehicle.shortDescription, price_per_day: vehicle.pricePerDay, security_deposit: vehicle.securityDeposit, passenger_capacity: vehicle.passengerCapacity, sleeping_capacity: vehicle.sleepingCapacity, fuel_type: vehicle.fuelType, transmission: vehicle.transmission, dimensions: vehicle.dimensions, driving_requirements: vehicle.drivingRequirements, amenities: vehicle.amenities, facilities: vehicle.facilities, images: vehicle.images, video_url: vehicle.videoUrl, status: vehicle.status, featured: vehicle.featured });

export async function getVehicles(): Promise<Vehicle[]> { const { data, error } = await createClient().from("vehicles").select("*").order("created_at", { ascending: false }); if (error) throw error; return (data ?? []).map((row) => fromRow(row)); }
export async function createVehicle(vehicle: Vehicle): Promise<Vehicle> { const { data, error } = await createClient().from("vehicles").insert(toRow(vehicle)).select().single(); if (error) throw error; return fromRow(data); }
export async function updateVehicle(vehicle: Vehicle): Promise<Vehicle> { const { data, error } = await createClient().from("vehicles").update(toRow(vehicle)).eq("id", vehicle.id).select().single(); if (error) throw error; return fromRow(data); }
export async function deleteVehicle(id: string): Promise<void> { const { error } = await createClient().from("vehicles").delete().eq("id", id); if (error) throw error; }
