"use client";

import Image from "next/image";
import { useState } from "react";
import { Bell, BookOpen, Check, CircleHelp, CreditCard, FileText, Heart, Home, LogOut, Map, MessageCircle, Settings, Star, UserRound, Wallet } from "lucide-react";
import { Button, ButtonLink, Card, CardContent, CardHeader, CardTitle, FormField, Input, StatusBadge, Textarea } from "@/components/ui";
import { getBookings, getCustomers, getDestinations, getOffers, getSettings, getVehicles } from "@/lib/data";
import { formatCurrency } from "@/lib/utils";
import { useVansStore } from "@/lib/store/VansStore";
import { BookingTimeline } from "@/components/customer/BookingTimeline";

const sections = [
  ["Dashboard", Home], ["My Bookings", BookOpen], ["Saved Vans", Heart], ["Road Trips", Map], ["Offers & Rewards", Star], ["Payments", Wallet], ["Documents", FileText], ["Notifications", Bell], ["Support", CircleHelp], ["Profile", UserRound], ["Settings", Settings],
] as const;
type SectionName = (typeof sections)[number][0];

function PanelCard({ title, children }: { title: string; children: React.ReactNode }) { return <Card className="customer-card"><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent>{children}</CardContent></Card>; }

export function CustomerPanel() {
  const [section, setSection] = useState<SectionName>("Dashboard");
  const bookings = getBookings(); const customer = getCustomers()[0]; const offers = getOffers(); const destinations = getDestinations(); const settings = getSettings();
  const { vehicles, savedVanIds, toggleSavedVan } = useVansStore(); const savedVans = vehicles.filter((vehicle) => savedVanIds.includes(vehicle.id)); const booking = bookings.find((item) => item.status === "confirmed") ?? bookings[0];
  const go = (next: SectionName) => setSection(next);
  return <div className="customer-panel min-h-screen bg-sand-100"><header className="border-b border-sand-200 bg-sand-50"><div className="container-wide flex items-center justify-between py-6"><div><p className="eyebrow">Customer panel</p><h1 className="mt-2 font-display text-3xl font-bold">Ready for your next adventure?</h1></div><ButtonLink href="/" variant="outline" size="sm"><LogOut className="h-4 w-4" /> Exit</ButtonLink></div></header><div className="container-wide grid gap-8 py-8 lg:grid-cols-[230px_1fr]"><aside className="hidden lg:block"><nav className="sticky top-24 space-y-1">{sections.map(([label, Icon]) => <button key={label} type="button" onClick={() => setSection(label)} className={`flex w-full items-center gap-3 rounded-lg px-4 py-3 text-left text-sm font-semibold transition-colors ${section === label ? "bg-forest-700 text-sand-50 shadow-soft" : "text-ink/70 hover:bg-sand-200"}`}><Icon className="h-4 w-4" />{label}{label === "Notifications" && <span className="ml-auto rounded-full bg-accent-500 px-2 py-0.5 text-[10px] text-white">3</span>}</button>)}</nav></aside><main className="min-w-0 pb-20 lg:pb-0">{section === "Dashboard" && <Dashboard booking={booking} customer={customer} savedVans={savedVans} go={go} />}{section === "My Bookings" && <Bookings bookings={bookings} />}{section === "Saved Vans" && <SavedVans savedVans={savedVans} toggleSavedVan={toggleSavedVan} />}{section === "Road Trips" && <Inspiration destinations={destinations} />}{section === "Offers & Rewards" && <Offers offers={offers} />}{section === "Payments" && <Payments bookings={bookings} />}{section === "Documents" && <Documents customer={customer} />}{section === "Notifications" && <Notifications />}{section === "Support" && <Support settings={settings} />}{section === "Profile" && <Profile customer={customer} />}{section === "Settings" && <AccountSettings />}</main></div><nav className="customer-bottom-nav fixed inset-x-0 bottom-0 z-40 flex justify-around border-t border-sand-200 bg-sand-50/95 px-2 py-2 backdrop-blur lg:hidden">{sections.slice(0, 5).map(([label, Icon]) => <button key={label} type="button" onClick={() => setSection(label)} className={`flex flex-col items-center gap-1 px-3 py-1 text-[10px] font-semibold ${section === label ? "text-forest-700" : "text-sand-500"}`}><Icon className="h-5 w-5" />{label === "Dashboard" ? "Home" : label.split(" ")[0]}</button>)}</nav></div>;
}

function Dashboard({ booking, customer, savedVans, go }: { booking: ReturnType<typeof getBookings>[number]; customer: ReturnType<typeof getCustomers>[number]; savedVans: ReturnType<typeof getVehicles>; go: (section: SectionName) => void }) { const vehicle = getVehicles().find((item) => item.id === booking.vehicleId) ?? getVehicles()[0]; return <div className="space-y-6 animate-fade-in"><div className="grid gap-4 sm:grid-cols-3"><Metric label="Total trips" value={customer.totalBookings} /><Metric label="Pending actions" value={2} /><Metric label="Saved vans" value={savedVans.length} /></div><BookingTimeline current={booking.status === "completed" ? 5 : 1} /><Card className="overflow-hidden"><div className="grid lg:grid-cols-[0.8fr_1.2fr]"><div className="relative min-h-56"><Image src={vehicle.images[0]} alt={vehicle.name} fill className="object-cover" sizes="(min-width: 1024px) 40vw, 100vw" /></div><div className="bg-forest-700 p-7 text-sand-50"><p className="text-sm text-forest-100">Next adventure</p><h2 className="mt-2 font-display text-3xl font-bold text-sand-50">{vehicle.name}</h2><p className="mt-2 text-forest-100">{booking.startDate} to {booking.endDate} · {booking.pickupLocation}</p><div className="mt-6 flex flex-wrap gap-3"><Button onClick={() => go("My Bookings")}>View booking</Button><Button variant="outline" className="border-forest-300 text-sand-50 hover:bg-forest-600" onClick={() => go("Support")}>Contact support</Button></div></div></div></Card><div className="grid gap-6 md:grid-cols-2"><PanelCard title="Offers preview"><p className="text-sm text-sand-500">New seasonal offers are waiting for your next escape.</p><Button variant="link" className="mt-4" onClick={() => go("Offers & Rewards")}>View offers <span aria-hidden="true">→</span></Button></PanelCard><PanelCard title="Notifications"><p className="flex gap-3 text-sm"><Bell className="h-4 w-4 text-accent-600" /> Your booking confirmation is ready to view.</p><Button variant="link" className="mt-4" onClick={() => go("Notifications")}>See all notifications</Button></PanelCard></div></div>; }
function Metric({ label, value }: { label: string; value: number }) { return <Card className="customer-metric"><CardContent className="p-5"><p className="text-sm text-sand-500">{label}</p><p className="mt-2 font-display text-4xl font-bold">{value}</p><p className="mt-2 text-xs font-semibold text-forest-600">↑ Demo trend</p></CardContent></Card>; }
function Bookings({ bookings }: { bookings: ReturnType<typeof getBookings> }) { return <PanelCard title="My bookings"><div className="space-y-4">{bookings.map((booking) => <div key={booking.id} className="customer-list-row grid gap-4 rounded-xl border border-sand-200 p-5 sm:grid-cols-[1fr_auto_auto]"><div><p className="font-display text-xl font-bold">{booking.bookingNumber}</p><p className="mt-1 text-sm text-sand-500">{booking.startDate} · {booking.pickupLocation} to {booking.dropLocation}</p><p className="mt-2 text-sm">Rental {formatCurrency(booking.rentalAmount)} · Deposit {formatCurrency(booking.securityDeposit)}</p></div><StatusBadge status={booking.status} /><div className="flex gap-2"><Button size="sm" variant="outline">View details</Button><Button size="sm" variant="ghost">Support</Button></div></div>)}</div></PanelCard>; }
function SavedVans({ savedVans, toggleSavedVan }: { savedVans: ReturnType<typeof getVehicles>; toggleSavedVan: (id: string) => void }) { return <PanelCard title="Saved vans"><div className="grid gap-4 md:grid-cols-2">{savedVans.length ? savedVans.map((vehicle) => <div key={vehicle.id} className="customer-list-row flex items-center justify-between rounded-xl border border-sand-200 p-4"><div><p className="font-display text-lg font-bold">{vehicle.name}</p><p className="text-sm text-sand-500">{formatCurrency(vehicle.pricePerDay)} / day</p></div><div className="flex gap-2"><Button size="sm" variant="ghost" onClick={() => toggleSavedVan(vehicle.id)}>Remove</Button><ButtonLink href={`/vans/${vehicle.slug}`} size="sm">View</ButtonLink></div></div>) : <EmptyState text="No saved vans yet. Explore the fleet and tap the heart on a van you love." />}</div></PanelCard>; }
function Inspiration({ destinations }: { destinations: ReturnType<typeof getDestinations> }) { return <PanelCard title="Travel inspiration"><p className="mb-5 rounded-xl bg-accent-50 p-4 text-sm text-accent-800">Suggestions only. Booking never requires a route or itinerary. Pick a van, dates, and locations, then travel your own way.</p><div className="grid gap-4 md:grid-cols-2">{destinations.map((destination) => <div key={destination.id} className="rounded-xl border border-sand-200 p-5"><h3 className="font-display text-xl font-bold">{destination.name}</h3><p className="mt-2 text-sm text-sand-500">{destination.shortDescription}</p><p className="mt-3 text-xs uppercase tracking-wider text-accent-600">{destination.recommendedDuration}</p></div>)}</div></PanelCard>; }
function Offers({ offers }: { offers: ReturnType<typeof getOffers> }) { return <PanelCard title="Offers & rewards"><div className="grid gap-4 md:grid-cols-2">{offers.map((offer) => <div key={offer.id} className="customer-list-row rounded-xl border border-sand-200 p-5"><p className="font-display text-xl font-bold">{offer.name}</p><p className="mt-2 text-sm text-sand-500">{offer.description}</p><p className="mt-4 font-bold text-accent-600">{offer.discountPercent}% off · static coupon</p><Button size="sm" variant="outline" className="mt-4">Apply demo offer</Button></div>)}</div><div className="mt-5 rounded-xl bg-forest-700 p-5 text-sand-50"><p className="text-sm text-forest-100">Reward points</p><p className="mt-2 font-display text-3xl font-bold text-sand-50">1,240 pts</p></div></PanelCard>; }
function Payments({ bookings }: { bookings: ReturnType<typeof getBookings> }) { return <PanelCard title="Payments & transactions"><div className="space-y-4">{bookings.map((booking) => <div key={booking.id} className="flex flex-wrap justify-between gap-3 border-b border-sand-200 pb-4"><div><p className="font-semibold">{booking.bookingNumber}</p><p className="text-sm text-sand-500">Rental and deposit</p></div><div className="text-right"><p className="font-semibold">{formatCurrency(booking.totalAmount)}</p><StatusBadge status={booking.paymentStatus} /></div></div>)}</div></PanelCard>; }
function Documents({ customer }: { customer: ReturnType<typeof getCustomers>[number] }) { return <PanelCard title="Driving & verification documents"><div className="space-y-3">{["Driving Licence", "Government ID", "Address Proof"].map((name, index) => <div key={name} className="customer-list-row flex flex-wrap items-center justify-between gap-3 rounded-xl border border-sand-200 p-4"><div><p className="font-semibold">{name}</p><p className="text-xs text-sand-500">Upload date · static placeholder</p></div><StatusBadge status={index === 0 && customer.documents.length ? "verified" : "pending"} /><Button size="sm" variant="outline">Upload</Button></div>)}</div></PanelCard>; }
function Notifications() { return <PanelCard title="Notifications"><div className="space-y-4">{["Booking confirmation received", "Payment confirmation received", "Pickup reminder: 24 hours to go", "Offer unlocked: Early Bird Special", "Document verification update"].map((item, index) => <div key={item} className={`flex gap-3 rounded-xl p-4 ${index < 3 ? "bg-accent-50" : "bg-sand-100"}`}><Bell className="h-4 w-4 text-accent-600" /><p className="text-sm">{item}</p>{index < 3 && <span className="ml-auto h-2 w-2 rounded-full bg-accent-500" />}</div>)}</div></PanelCard>; }
function Support({ settings }: { settings: ReturnType<typeof getSettings> }) { return <PanelCard title="Support & contact"><p className="text-sand-500">Need help with a booking or vehicle handover? This demo keeps support ready for the future ticket/chat phase.</p><div className="mt-6 grid gap-3 sm:grid-cols-3"><a className="rounded-xl border border-sand-200 p-4 transition hover:-translate-y-0.5 hover:shadow-soft" href={`tel:${settings.phone}`}><MessageCircle className="h-5 w-5 text-forest-600" /><strong className="mt-3 block">Call support</strong></a><a className="rounded-xl border border-sand-200 p-4 transition hover:-translate-y-0.5 hover:shadow-soft" href={`mailto:${settings.email}`}><CreditCard className="h-5 w-5 text-forest-600" /><strong className="mt-3 block">Email support</strong></a><Button variant="outline">Report an issue</Button></div></PanelCard>; }
function Profile({ customer }: { customer: ReturnType<typeof getCustomers>[number] }) { return <PanelCard title="My profile"><div className="grid gap-5 sm:grid-cols-2"><FormField label="Full name"><Input defaultValue={customer.name} /></FormField><FormField label="Email"><Input defaultValue={customer.email} /></FormField><FormField label="Mobile number"><Input defaultValue={customer.phone} /></FormField><FormField label="Date of birth"><Input type="date" defaultValue={customer.dateOfBirth} /></FormField><FormField label="Address" className="sm:col-span-2"><Input defaultValue={`${customer.city}, Maharashtra`} /></FormField><FormField label="Emergency contact"><Input placeholder="Name and phone" /></FormField><Button>Save profile</Button></div></PanelCard>; }
function AccountSettings() { return <PanelCard title="Account settings"><div className="space-y-5"><label className="flex gap-3 text-sm"><input type="checkbox" defaultChecked /> Email booking updates</label><label className="flex gap-3 text-sm"><input type="checkbox" defaultChecked /> Pickup and return reminders</label><FormField label="Change password"><Input type="password" placeholder="New password" /></FormField><Button>Save preferences</Button><Button variant="outline" className="ml-3">Delete account</Button></div></PanelCard>; }
function EmptyState({ text }: { text: string }) { return <div className="rounded-xl border border-dashed border-sand-300 bg-sand-50 p-10 text-center text-sm text-sand-500"><Heart className="mx-auto h-8 w-8 text-accent-500" /><p className="mx-auto mt-4 max-w-sm">{text}</p><ButtonLink href="/vans" className="mt-5">Explore vans</ButtonLink></div>; }
