"use client";

import Image from "next/image";
import { useEffect, useState } from "react";
import { ArrowRight, CalendarDays, Check, MapPin } from "lucide-react";
import { ButtonLink, Card, CardContent, Container } from "@/components/ui";
import { PageContent } from "@/components/layout/PageBanner";
import { getPackageBySlug, getPublishedPackages, type PackageRecord } from "@/lib/services/packages";
import { formatCurrency } from "@/lib/utils";

function PackageBanner({ title, description }: { title: string; description: string }) {
  return <section className="bg-forest-700 py-16 text-sand-50 sm:py-24"><Container><p className="mb-4 text-sm font-bold uppercase tracking-[0.2em] text-accent-300">Curated road trips</p><h1 className="max-w-4xl font-display text-5xl font-bold leading-none text-sand-50 sm:text-7xl">{title}</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-forest-100">{description}</p></Container></section>;
}

export function PublicPackagesPage() {
  const [packages, setPackages] = useState<PackageRecord[]>([]);
  const [error, setError] = useState("");
  useEffect(() => { getPublishedPackages().then(setPackages).catch((reason) => setError(reason instanceof Error ? reason.message : "Packages are unavailable right now.")); }, []);
  return <><PackageBanner title="Pick a place. We will bring the feeling." description="Young, easy-going road trips around Mahabaleshwar, Panchgani, and Tapola. Choose a package when you want a little more structure, or rent a van and make your own route." /><PageContent>{error ? <Card><CardContent className="p-8 text-center text-sm text-sand-500">{error}</CardContent></Card> : packages.length === 0 ? <Card className="border-dashed"><CardContent className="p-12 text-center"><CalendarDays className="mx-auto h-10 w-10 text-sand-400" /><h2 className="mt-5 font-display text-2xl font-bold">Fresh routes are landing soon</h2><p className="mt-2 text-sand-500">Our team is currently shaping the first live packages.</p></CardContent></Card> : <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{packages.map((item, index) => <article key={item.id} className="group animate-slide-up overflow-hidden rounded-xl border border-sand-200 bg-sand-50 shadow-soft" style={{ animationDelay: `${index * 80}ms` }}><div className="relative aspect-[4/3] overflow-hidden bg-forest-100">{item.images[0] ? <Image src={item.images[0]} alt={item.title} fill className="object-cover transition-transform duration-500 group-hover:scale-105" sizes="(min-width: 1024px) 33vw, 100vw" /> : <div className="flex h-full items-center justify-center text-forest-600"><MapPin className="h-10 w-10" /></div>}<span className="absolute left-4 top-4 rounded-full bg-sand-50/95 px-3 py-1 text-xs font-bold uppercase tracking-wider text-forest-700">{item.location}</span></div><div className="p-6"><h2 className="font-display text-2xl font-bold">{item.title}</h2><p className="mt-3 line-clamp-3 text-sm leading-relaxed text-sand-500">{item.description}</p><div className="mt-5 flex items-center justify-between border-y border-sand-200 py-4 text-sm"><span>{item.duration_days} days</span><strong className="font-display text-xl">{formatCurrency(Number(item.price))}</strong></div><ButtonLink href={`/packages/${item.slug}`} className="mt-5 w-full">View package <ArrowRight className="h-4 w-4" /></ButtonLink></div></article>)}</div>}</PageContent></>;
}

export function PublicPackageDetailsPage({ slug }: { slug: string }) {
  const [item, setItem] = useState<PackageRecord | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { getPackageBySlug(slug).then(setItem).catch((reason) => setError(reason instanceof Error ? reason.message : "Package unavailable.")); }, [slug]);
  if (error) return <><PackageBanner title="This route moved." description={error} /><PageContent><ButtonLink href="/packages">Back to packages</ButtonLink></PageContent></>;
  if (!item) return <><PackageBanner title="Loading your route..." description="Pulling the latest live package details." /><PageContent><p className="text-sand-500">Loading package details...</p></PageContent></>;
  const itinerary = Array.isArray(item.itinerary) ? item.itinerary : [];
  return <><PackageBanner title={item.title} description={item.description} /><PageContent><div className="grid gap-10 lg:grid-cols-[1.15fr_0.85fr]"> <div>{item.images.length > 0 && <div className="grid gap-3 sm:grid-cols-2">{item.images.map((image, index) => <div key={image} className={`${index === 0 ? "sm:col-span-2 aspect-[16/8]" : "aspect-video"} relative overflow-hidden rounded-xl`}><Image src={image} alt={`${item.title} image ${index + 1}`} fill className="object-cover" sizes="(min-width: 640px) 50vw, 100vw" /></div>)}</div>}<div className="mt-10"><p className="text-sm font-bold uppercase tracking-widest text-accent-600">The route</p><div className="mt-5 space-y-0">{itinerary.map((day, index) => <div key={`${day.day}-${index}`} className="relative flex gap-5 pb-8 last:pb-0"><div className="relative flex w-9 shrink-0 justify-center"><span className="z-10 flex h-9 w-9 items-center justify-center rounded-full bg-accent-500 text-sm font-bold text-white">{day.day}</span>{index < itinerary.length - 1 && <span className="absolute top-9 h-full w-px bg-accent-200" />}</div><div><h2 className="font-display text-2xl font-bold">{day.title}</h2><p className="mt-2 leading-relaxed text-sand-500">{day.description}</p>{day.activities && <ul className="mt-3 space-y-2 text-sm text-ink/70">{day.activities.map((activity) => <li key={activity} className="flex gap-2"><Check className="h-4 w-4 shrink-0 text-accent-600" />{activity}</li>)}</ul>}</div></div>)}</div></div></div><aside className="h-fit rounded-xl bg-forest-700 p-7 text-sand-50 lg:sticky lg:top-24"><p className="text-sm text-forest-100">{item.location} · {item.duration_days} days</p><p className="mt-2 font-display text-4xl font-bold text-sand-50">{formatCurrency(Number(item.price))}</p><p className="mt-2 text-sm text-forest-100">Per package, before optional van rental extras.</p><div className="mt-7 border-t border-forest-500 pt-5"><p className="font-semibold">Included</p><ul className="mt-3 space-y-2 text-sm text-forest-100">{item.inclusions.map((value) => <li key={value} className="flex gap-2"><Check className="h-4 w-4 shrink-0 text-accent-300" />{value}</li>)}</ul>{item.exclusions.length > 0 && <><p className="mt-6 font-semibold">Not included</p><ul className="mt-3 space-y-2 text-sm text-forest-100">{item.exclusions.map((value) => <li key={value}>• {value}</li>)}</ul></>}</div><ButtonLink href={`/book?package=${item.slug}`} className="mt-7 w-full">Select this package <ArrowRight className="h-4 w-4" /></ButtonLink></aside></div></PageContent></>;
}
